from app.models.user import User
from app.models.discipline import Discipline
from app.models.teacher import Teacher
from app.models.student import Student
from app.models.school_class import SchoolClass
from app.models.enrollment import Enrollment
from app.models.notice import Notice
from app.models.notification import Notification
from app.models.calendar_event import CalendarEvent
from app.models.grade import Grade
from app.models.attendance import Attendance
from app.models.assignment import Assignment
from app.models.submission import Submission